#include "help.h"

char *help_minimal = ""
	"usage: base-convert initial_base final_base numbers...\n"
	"       base-convert {-h|--help}                       \n";
char *help_full = ""
	"Usage                                                                           \n"
	"        base-convert initial_base final_base numbers...                         \n"
	"        base-convert {-h|--help}                                                \n"
	"                                                                                \n"
	"Description                                                                     \n"
	"        Convert numbers from one base representation to another.                \n"
	"                                                                                \n"
	"Options                                                                         \n"
	"        numbers...          : The numbers to be converted to another base.      \n"
	"                              These must be written in the representation of the\n"
	"                              initial base.                                     \n"
	"        initial_base        : Serve as the initial base for the numbers.        \n"
	"        final_base          : The base that the numbers will converts into.     \n"
	"        -h, --help          : Show this help file.                              \n"
	"                                                                                \n"
	"Examples                                                                        \n"
	"                base-convert 2 10 110100100 1000101                             \n"
	"        Changes the representation of the numbers '110100100' and '1000101' from\n"
	"        base2 into base10.                                                      \n";
