#include "help.h"

char *help_minimal = ""
	"usage: base-convert base1 base2 number                                           \n"
	"       base-convert {-h|--help}                                                  \n";
char *help_full = ""
	"Usage                                                                            \n"
	"        base-convert base1 base2 number                                          \n"
	"        base-convert {-h|--help}                                                 \n"
	"                                                                                 \n"
	"Description                                                                      \n"
	"        Convert numbers from one base representation to another.                 \n"
	"                                                                                 \n"
	"Options                                                                          \n"
	"        number               : The number to be converted to another base.       \n"
	"                               This must be written in the representation of the \n"
	"                               initial base.                                     \n"
	"        base1                : Serve as the initial base for the number.         \n"
	"        base2                : The base that the number will converts into.      \n"
	"        -h, --help           : Show this help file.                              \n"
	"                                                                                 \n"
	"Examples                                                                         \n"
	"                base-convert 2 10 1010010001010101                               \n"
	"        Show the representation of the number '1010010001010101' from base2 into \n"
	"        base10.                                                                  \n"
	"                                                                                 \n";
